//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodBasket
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MenuItem
    {
        public int MenuItemId { get; set; }
        public int MenuCatID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Order_ID { get; set; }
        public string Visible { get; set; }
        public Nullable<int> Quantity { get; set; }
    }
}
