//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodBasket
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Order
    {
        public string Order_ID { get; set; }
        public string Emp_ID { get; set; }
        public string MenuItem_ID { get; set; }
        public Nullable<decimal> Item_Price { get; set; }
        public Nullable<int> Order_Quantity { get; set; }
        public Nullable<decimal> Item_TotalPrice { get; set; }
    }
}
