//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodBasket
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MenuCategory
    {
        public int MenuCatID { get; set; }
        public string Cat_Name { get; set; }
        public string Order_ID { get; set; }
    }
}
